project:
  type: website

website:
  title: "Arnab Das"
  navbar:
    left:
      - text: Projects
        href: project.qmd
      - text: Visualization 
        href: empty.qmd
    right:
      - icon: github
        href: https://github.com/4rnab20
        
format:
  html:
    theme: 
      dark: [Cosmo, custom.scss]
      light: [Cosmo, custom2.scss]
    css: styles.css
    code-overflow: scroll
editor: visual

