project:
  type: website
  output-dir: docs

website:
  favicon: adlogo.png
  title: "Arnab Das"
  navbar:
    left:
      - text: Projects
        href: project.qmd
      - text: Visualizations 
        href: visuals.qmd
  
format:
  html:
    theme: 
      dark: [Cosmo, custom.scss]
      light: [Cosmo, custom2.scss]
    css: styles.css
    code-overflow: scroll
editor: visual

